### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by PaulC91** [ewenme/discogger#2]
Hey Ewen, really liking the look of this - great job!

Very interested in helping out in any way possible. Let me know what features you're looking to add going forward and I'll try and dig into some of them.

Cheers,
Paul

**Comment by ewenme** [comment]
Cheers mate! Been a long overdue proj (really should've came _before_ the Shiny app I made using the same bleedin' API)...

Think I will start to add some possible features as issues, so feel free to assign yourself to those if your into them, but similarly if you had any ideas for new things then we can chat here or whatever. Nice one!

**Comment by PaulC91** [comment]
Sounds good man. I'll have look through the API docs and see if I can come up with some ideas!

**Comment by PaulC91** [comment]
playing around with some mapping

https://gist.github.com/PaulC91/ec4143d29bb19b7176d38eace018e4ff
