### ISSUE TITLE
Simplify collection output

### ISSUE THREAD

**Issue by sharlagelfand** [ewenme/discogger#4]
The output from `discogs_user_collection()` is quite complicated due to what the API returns -- lots of nested lists, one for each label/artist etc. It's be awesome to have a "simplified" version of the output that returns just the "name" element for each of those nested lists so it's possible to output a data frame with release name/label/artist etc for the whole collection, instead of a list of lists.

This issue is not a suggestion of work for _you_ to do @ewenme -- I'd actually like to try my hand at this if it's something you'd find valuable, or if it's not something you're already working on. Figured I'd check here first :)

**Comment by sharlagelfand** [comment]
To clarify I'm not proposing changing the existing `discogs_user_collection()` function, but perhaps creating a function that can clean up that output, or a different, complementary function altogether that would return simplified output

**Comment by ewenme** [comment]
I agree, a simplified user collection output would be wicked. If you wanted to look at this, that would be wicked too :)
I think a complementary function that returns a tidy dataframe for a users collection is a sensible approach. What do you think?

**Comment by sharlagelfand** [comment]
yeah, i think that makes sense! i'd be happy to take a stab at it

**Comment by sharlagelfand** [comment]
@ewenme wouldn't you know, i finally decided to use discogger for a personal project and have spent the last few days trying to figure out how to simplify the collection output for myself (since i obviously didn't follow up on this issue).

thanks for this!!

**Comment by ewenme** [comment]
Oh, I was in the same boat so went ahead! (Someone else is using it, yay).
