### ISSUE TITLE
discogs_artist_releases function

### ISSUE THREAD

**Issue by RomainBousquet** [ewenme/discogger#5]
Hi Ewen, great tool...
I am experiencing an issue when using the discogs_artist_releases function - i get the error: "Error in bind_rows_(x, .id) : Argument 2 must be length 2, not 1".
Any idea why that is?

**Comment by ewenme** [comment]
Hi Romain, 
Best if you can provide a reproducible example demonstrating the error - [reprex](https://github.com/tidyverse/reprex) is good for helping with that.
